# REQUERING POWER STATE
- id: cd49661388ab47d99886f97c5a4d7c46
  alias: Power state on HA start-up
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/front_porch/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/front_porch2/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/main_bedroom/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/main_bedroom2/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/childroom/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_a1/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_a2/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_a3/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/school_bell/POWER1
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_b1/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_b2/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_b3/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/bathroom/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/kitchen/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/main_bedroom_ac/POWER

# RESTART HA TO KEEP IT FRESH
- alias: Restart HA Schedule
  trigger:
    platform: time
    at: '02:00:00'
  action:
    - service: homeassistant.restart

# LIGHT PRIORITY
- alias: Turn On Light Priority
  trigger:
    platform: state
    entity_id: binary_sensor.pir_1, binary_sensor.pir_3
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.dapur
        - light.kamar_mandi
    - service: timer.cancel
      data:
        entity_id: timer.priority_light
    - service: timer.start
      data:
        entity_id: timer.priority_light
- alias: Turn Off Light Priority
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.priority_light
  action:
    service: homeassistant.turn_off
    entity_id: 
      - light.dapur
      - light.kamar_mandi

# ALARM MODE
- alias: Turn On Alarm (Sensor)
  trigger:
    platform: state
    entity_id: binary_sensor.pir_4
    to: 'on'
  condition:
    condition: time
    after: '21:00:00'
    before: '03:00:00'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.front_porch
    - service: timer.start
      data:
        entity_id: timer.front_porch
    - service: homeassistant.turn_on
      entity_id: light.lollin
- alias: Turn Off Alarm (Sensor)
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.front_porch
  condition:
    condition: time
    after: '23:00:00'
    before: '03:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.lollin

# FRONT PORCH
- alias: Turn On Front Porch (Sensor)
  trigger:
    platform: state
    entity_id: binary_sensor.pir_4
    to: 'on'
  condition:
    condition: time
    after: '03:00:00'
    before: '21:00:00'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.front_porch
    - service: timer.start
      data:
        entity_id: timer.front_porch
- alias: Turn Off Front Porch1 (AM)
  trigger:
    platform: sun
    event: sunrise
    offset: '-00:15:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.teras_depan1
- alias: Turn Off Front Porch2 (AM)
  trigger:
    platform: sun
    event: sunrise
    offset: '-02:45:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.teras_depan2
- alias: Turn On Front Porch1 (PM)
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    - service: homeassistant.turn_on
      entity_id: light.teras_depan1
- alias: Turn On Front Porch2 (PM)
  trigger:
    platform: sun
    event: sunset
    offset: "00:30:00"
  action:
    - service: homeassistant.turn_on
      entity_id: light.teras_depan2
      
# MAIN BEDROOM
- alias: Turn On Main Bedroom (Sensor)
  trigger:
    platform: state
    entity_id: binary_sensor.pir_1
    to: 'on'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.main_bedroom
    - service: timer.start
      data:
        entity_id: timer.main_bedroom
- alias: Turn Off Main Bedroom (Sensor)
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.main_bedroom
  condition:
    condition: time
    after: '21:00:00'
    before: '03:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.kamar_utama
    
- alias: Turn On Main Bedroom (AM)
  trigger:
    platform: time
    at: '02:30:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kamar_utama
- alias: Turn On Main Bedroom2 (AM)
  trigger:
    platform: time
    at: '02:45:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kamar_utama2
- alias: Turn Off Main Bedroom2 (PM)
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.kamar_utama2
- alias: Turn Off Main Bedroom (PM)
  trigger:
    platform: time
    at: '23:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.kamar_utama
      
# CHILDROOM
- alias: Turn On Childroom (Sensor)
  trigger:
    platform: state
    entity_id: binary_sensor.pir_1
    to: 'on'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.childroom
    - service: timer.start
      data:
        entity_id: timer.childroom
- alias: Turn Off Childroom (Sensor)
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.childroom
  condition:
    condition: time
    after: '21:00:00'
    before: '03:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.kamar_anak
- alias: Turn On Childroom (AM)
  trigger:
    platform: time
    at: '03:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kamar_anak
- alias: Turn Off Childroom (PM)
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.kamar_anak

# CLASSROOM A - SENSOR 
- alias: Turn On Classroom A (Sensor)
  trigger:
    platform: state
    entity_id: binary_sensor.radar_1
    to: 'on'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.classroom_a
    - service: timer.start
      data:
        entity_id: timer.classroom_a
- alias: Turn Off Classroom A2 (Sensor)
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.classroom_a
  condition:
    condition: time
    after: '07:00:00'
    before: '18:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.kelas_a2
        
# CLASSROOM A - SCHEDULE AM
- alias: Turn On Classroom A1 (AM) 
  trigger:
    platform: time
    at: '04:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kelas_a1
- alias: Turn On Classroom A2 (AM)
  trigger:
    platform: time
    at: '05:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kelas_a2
- alias: Turn Off Classroom A (AM-1)
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.kelas_a1
        - light.kelas_a2
- alias: Turn Off Classroom A (AM-2)
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.kelas_a1
        - light.kelas_a2
      
# CLASSROOM A - SCHEDULE PM
- alias: Turn On Classroom A (PM) 
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.kelas_a1
        - light.kelas_a2
- alias: Turn Off Classroom A2 (PM)
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.kelas_a2
- alias: Turn Off Classroom A (PM-1)
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    condition: time
    weekday:
      - sun
      - mon
      - tue
      - wed
      - fri
      - sat
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.kelas_a1
        - light.kelas_a2
- alias: Turn Off Classroom A (PM-2)
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    condition: time
    weekday:
      - thu
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.kelas_a1
        - light.kelas_a2

# CLASSROOM B - SENSOR
- alias: Turn On Classroom B (Sensor)
  trigger:
    platform: state
    entity_id: binary_sensor.pir_2, binary_sensor.pir_3
    to: 'on'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.classroom_b
    - service: timer.start
      data:
        entity_id: timer.classroom_b
    - service: homeassistant.turn_on
      entity_id: 
        - light.kelas_b1
        - light.kelas_b2
        - light.kelas_b3
- alias: Turn Off Classroom B (Sensor)
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.classroom_b
  condition:
    condition: time
    after: '12:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: 
      - light.kelas_b1
      - light.kelas_b2
      - light.kelas_b3
      
# CLASSROOM B - SCHEDULE AM
- alias: Turn On Classroom B (AM)
  trigger:
    platform: time
    at: '05:15:00'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.kelas_b1
        - light.kelas_b2
        - light.kelas_b3
- alias: Turn Off Classroom B (AM-1)
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: time
    weekday:
      - sun
      - sat
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.kelas_b1
        - light.kelas_b2
        - light.kelas_b3
- alias: Turn Off Classroom B (AM-2)
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.kelas_b1
        - light.kelas_b2
        - light.kelas_b3

# CLASSROOM B - SCHEDULE PM
- alias: Turn On Classroom B (PM)
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.kelas_b1
        - light.kelas_b2
        - light.kelas_b3
- alias: Turn Off Classroom B (PM)
  trigger:
    platform: time
    at: '17:30:00'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.kelas_b1
        - light.kelas_b2
        - light.kelas_b3
- alias: Turn On Classroom B (PM-2)
  trigger:
    platform: time
    at: '18:15:00'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.kelas_b1
        - light.kelas_b2
        - light.kelas_b3
- alias: Turn Off Classroom B (PM-2)
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.kelas_b1
        - light.kelas_b2
        - light.kelas_b3

# SCHOOL BELL
- alias: Turn On School Bell In
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.bell_ring_in_break
- alias: Turn On School Bell Break
  trigger:
    platform: time
    at: '09:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.bell_ring_in_break
- alias: Turn On School Bell Out (A)
  trigger:
    platform: time
    at: '10:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.bell_ring_out
- alias: Turn On School Bell Out (B)
  trigger:
    platform: time
    at: '11:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.bell_ring_out

- alias: Turn On Lollin
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.lollin
- alias: Turn Off Lollin (Timer)
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.main_bedroom
  condition:
    condition: time
    after: '21:00:00'
    before: '03:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.lollin
