- id: cd49661388ab47d99886f97c5a4d7c46
  alias: Power state on HA start-up
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/front_porch/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/front_porch2/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/main_bedroom/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/main_bedroom2/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/childroom/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_a1/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_a2/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/school_bell/POWER1
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_b1/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_b2/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/classroom_b3/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/bathroom/POWER
  - service: mqtt.publish
    data:
      payload: ''
      topic: cmnd/kitchen/POWER
      
- alias: Motion Detected (PIR & RADAR)
  trigger:
    platform: state
    entity_id: binary_sensor.pir_1, binary_sensor.radar_1
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.lolin
        - light.dapur
        - light.kamar_mandi
    - service: timer.cancel
      data:
        entity_id: timer.light_priority
    - service: timer.start
      data:
        entity_id: timer.light_priority
      
- alias: Turn Off Light Priority
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.light_priority
  action:
    service: homeassistant.turn_off
    entity_id: 
      - light.lolin
      - light.dapur
      - light.kamar_mandi
