- id: light-off-temp-above-35
  alias: 'Turn off Light - Temperature above 35 '
  trigger:
    platform: numeric_state
    entity_id: sensor.ku_temperature
    above: 35
  action:
   service: homeassistant.turn_off
   entity_id: light.km_utama

- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/front_porch/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/front_porch2/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/main_bedroom/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/childroom/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/classroom_a1/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/classroom_a2/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/school_bell/POWER1"
        payload: ""
