- platform: mqtt
  name: "Radar 1"
  state_topic: "tele/radar/SENSOR"
  value_template: "{{value_json.Switch1}}"
- platform: mqtt
  name: "PIR 1"
  state_topic: "tele/pir/SENSOR"
  value_template: "{{value_json.Switch1}}"
- platform: mqtt
  name: "PIR 2"
  state_topic: "tele/pir_2/SENSOR"
  value_template: "{{value_json.Switch1}}"
- platform: mqtt
  name: "PIR 3"
  state_topic: "tele/pir_3/SENSOR"
  value_template: "{{value_json.Switch1}}"
- platform: mqtt
  name: "PIR 4"
  state_topic: "tele/pir_4/SENSOR"
  value_template: "{{value_json.Switch1}}"