homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jakarta
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor: !include sensor.yaml

light:
  - platform: mqtt
    name: "Teras Depan1"
    command_topic: "cmnd/front_porch/POWER"
    state_topic: "stat/front_porch/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Teras Depan2"
    command_topic: "cmnd/front_porch2/POWER"
    state_topic: "stat/front_porch2/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kamar Utama"
    command_topic: "cmnd/main_bedroom/POWER"
    state_topic: "stat/main_bedroom/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kamar Utama2"
    command_topic: "cmnd/main_bedroom2/POWER"
    state_topic: "stat/main_bedroom2/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kamar Anak"
    command_topic: "cmnd/childroom/POWER"
    state_topic: "stat/childroom/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kelas A1"
    command_topic: "cmnd/classroom_a1/POWER"
    state_topic: "stat/classroom_a1/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kelas A2"
    command_topic: "cmnd/classroom_a2/POWER"
    state_topic: "stat/classroom_a2/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kelas B1"
    command_topic: "cmnd/classroom_b1/POWER"
    state_topic: "stat/classroom_b1/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kelas B2"
    command_topic: "cmnd/classroom_b2/POWER"
    state_topic: "stat/classroom_b2/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kelas B3"
    command_topic: "cmnd/classroom_b3/POWER"
    state_topic: "stat/classroom_b3/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Kamar Mandi"
    command_topic: "cmnd/bathroom/POWER"
    state_topic: "stat/bathroom/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Dapur"
    command_topic: "cmnd/kitchen/POWER"
    state_topic: "stat/kitchen/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Lollin"
    command_topic: "cmnd/lollin/POWER"
    state_topic: "stat/lollin/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://192.168.1.26:3218

mqtt:
  broker: 192.168.1.26
  username: !secret mqtt_username
  password: !secret mqtt_password

timer:
  front_porch:
    duration: '00:05:00'
  priority_light:
    duration: '00:20:00'
  classroom_a:
    duration: '00:15:00'
  classroom_b:
    duration: '00:15:00'
  childroom:
    duration: '00:10:00'
  main_bedroom:
    duration: '00:05:00'

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home

#android_ip_webcam:
#  - host: 192.168.1.10
#    port: 8910
#    username: "firuze"
#    password: "347893Firuze"